### ISSUE TITLE
information

### ISSUE THREAD

**Issue by Indigofera** [hclimente/spada#2]
Could you please support more information especially output or results?

**Comment by hclimente** [comment]
Yes, sorry about that!

We are in the last stages of development, still defining the final outputs and fixing minor bugs. That's why not everything is yet well documented.

I have created a (work-in-progress) description of the outputs in the wiki at https://github.com/hclimente/spada/wiki/Output-files

While we work on it, let me know if I you have specific questions about spada.

**Comment by Indigofera** [comment]
Thanks for quick response. Yes, I have one more question. All switches after analyze (using command Spada switches), are they statistically significant?

**Comment by hclimente** [comment]
That's hard to answer with precision. In a way they are significant: each of the two transcripts must have a extreme variation between normal and tumor (>= 95% of the observed among normal samples). However, we are not computing any multiple test correction over these values, as it is an empirical p-value and has properties we can't deal with using standard methods. For example, very often the p-value is 0, that is, the observed variation is most extreme than the variation observed among control samples.

So instead, we try to account for multiple testing using heuristics. In our case, as you can read [in our paper](https://www.sciencedirect.com/science/article/pii/S221112471731104X), we relied on the number of samples: if the same switch is detected in many patients, then it is likely due to a biological effect and not just noise. Simplifying, if for a gene with 10 transcripts (90 possible switches) we observe 4 switches: 1 switch in 30 samples, and 3 other switches in only one sample, we will only consider the former as 'significant', if you will. 

At the moment this heuristic is not implemented in spada, as we prefer to let the user decide how they want to deal with it.

**Comment by Indigofera** [comment]
Thank you
